[project]
title = "My Project"
version = "0.1.0"
port = 8501
slug = "{project_slug}"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/logo.png"
primaryColor = "#F89613"

[data.ai_csv]
type = "csv"
path = "data/ai_dev_productivity.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 